config/routes.rb
Rails.application.routes.draw do

  get 'dashboard', to:"dashboard#index"

  namespace :admin do
    resources :templates
  end
  
  resources :reports do
    collection do
      get "templates"
    end
  end

  devise_for :users

  root "dashboard#index"
end

app/views/admin/templates/_form.html.haml
= form_for [:admin, @template], html: { id: "templates_form" } do |f|
  = error_field @template

  .report_fields_div
    .field
      = f.label :title
      = f.text_field :title
    - if @template.items.exists?
      - @template.items.each do |item|
        .field
          = f.label :item_name
          = text_field_tag "template[item_name][#{item.id}][]", item.name
          %a#remove_added_field
            %i.glyphicon.glyphicon-trash
    - else
      .field
        = f.label :item_name
        = text_field_tag "template[item_name][0][]"
        %a#remove_added_field
          %i.glyphicon.glyphicon-trash
    #item_name_div

    %a.btn.btn-primary#add_new_item Add new item
    .actions
      = f.submit 'Save'

app/views/admin/templates/edit.html.haml
- title "Edit Template: #{@template.title}"

= link_to 'Back', admin_templates_path, class: "back-btn"

%h1 Editing template

= render 'form'

app/views/admin/templates/index.html.haml
- title "Templates"

- unless @templates.empty?
  %h1 Listing templates

  %table.table
    %tr
      %th{width: "800"} Title
      %th{colspan:"3"}

    - @templates.each do |template|
      %tr
        %td= template.title
        %td= link_to 'Show', [:admin, template], class:"btn btn-success"
        %td= link_to 'Edit', edit_admin_template_path(template), class:"btn btn-info"
        %td= link_to 'Destroy', [:admin, template], :method => :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-danger"
- else
  %h1 Reports does not exists!

%br

= link_to 'New Template', new_admin_template_path, class:"btn btn-primary"

app/views/admin/templates/new.html.haml
- title "New Template"

= link_to 'Back', admin_templates_path, class: "back-btn"

%h1 New template

= render 'form'

app/views/admin/templates/show.html.haml
- title "Show Template: #{@template.title}"

= link_to 'Back', admin_templates_path, class: "back-btn"

= print_notice notice

%p
	%b Title:
	= @template.title
- if @template.items.exists?
	%h3 Item list
	%ol
		- @template.items.each do |item|
			%li= item.name

= link_to 'Edit', edit_admin_template_path(@template), class: "btn btn-info"