config/routes.rb
Rails.application.routes.draw do

  get 'dashboard', to:"dashboard#index"

  namespace :admin do
    resources :templates
  end
  
  resources :reports do
    collection do
      get "templates"
    end
  end

  devise_for :users

  root "dashboard#index"
end

app/models/report.rb
class Report
  include Mongoid::Document
  field :title, type: String

  belongs_to :template
  embeds_many :item_values

  validates_presence_of :title

  def template_obj
    Template.find(self.template_id)
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @reports = Report.all
    respond_with(@reports)
  end

  def show
    respond_with(@report)
  end

  def new
    @report = Report.new
    respond_with(@report)
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    @report.save
    respond_with([:admin, @report])
  end

  def update
    @report.update(report_params)
    respond_with([:admin, @report])
  end

  def destroy
    @report.destroy
    respond_with([:admin, @report])
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:title)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource :except => [:show, :index]
  skip_load_resource :only => [:create]

  respond_to :html

  def index
    @reports = Report.all
    respond_with(@reports)
  end

  def show
    @items_value = @report.item_values.group_by { |e| e.item_id }
    respond_with(@report)
  end

  def new
    @report = Report.new
    @template ||= nil

    unless params[:template].nil?
      @template = Template.find(params[:template])
    else
      not_found
    end

    respond_with(@report)
  end

  def templates
    @templates = Template.all
  end

  def edit
    @template = Template.find(@report.template_id)
  end

  def create
    @template = Template.find(report_params[:template_id])
    @report = Report.create(title: report_params[:title])
    @template.reports << @report

    unless report_params[:item_value].blank?
      report_params[:item_value].each { |item_id, items|
        items.each { |item_value|
          @report.item_values << ItemValue.new(value: item_value, item_id: item_id)
        }
      }
    end

    if @report.save
      flash[:notice] = "Report successfully create!"
      respond_with(@report)
    else
      render "new"
    end
  end

  def update
    @template = Template.find(report_params[:template_id])

    return render "edit" unless @report.update_attributes(title: report_params[:title])

    @report.item_values.clear

    unless report_params[:item_value].blank?
      report_params[:item_value].each { |item_id, items|
        items.each { |item_value|
          @report.item_values << ItemValue.new(value: item_value, item_id: item_id) unless item_value.empty?
        }
      }
    end

    flash[:notice] = "Report successfully update!"
    respond_with(@report)
  end

  def destroy
    @report.destroy
    respond_with(@report)
  end

  private
    def not_found
      raise ActionController::RoutingError.new('Not Found')
    end

    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit!
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for(@report) do |f|
  = error_field @report
  = hidden_field_tag "report[template_id]", @template.id
  .field
    = f.label :title
    = f.text_field :title
  - if @template.items.exists?
    %h3= "#{@template.title} Fields"
    - @template.items.each do |item|
      .field
        = f.label item.name
        - if @report.item_values.exists?
          - @report.item_values.each do |item_value|

            - if item.id === item_value.item_id
              %div
                = text_field_tag "report[item_value][#{item.id}][]", item_value.value
                %a#remove_added_field
                  %i.glyphicon.glyphicon-trash
      %div{id:"append_input_#{item.id}"}
        = text_field_tag "report[item_value][#{item.id}][]"
        %a#remove_added_field
          %i.glyphicon.glyphicon-trash
      %div{id:"item_#{item.id}"}
      = link_to "Add addition", "#", :"data-id" => item.id, id: "add_additon_value", class: "btn btn-xs btn-primary"

  .actions
    = f.submit 'Save'

app/views/reports/edit.html.haml
- title "Edit Report: #{@report.title}"

= link_to 'Back', reports_path, class: "back-btn"

%h1 Editing report

= render 'form'

app/views/reports/index.html.haml
- title "Reports"


- unless @reports.empty?
  %h1 Listing reports
  %table.table
    %tr
      %th{width: "800"} Title
      %th Template
      %th{colspan:"3"}

    - @reports.each do |report|
      %tr
        %td= report.title
        %td= report.template_obj.title
        %td= link_to 'Show', report, class:"btn btn-success"
        %td= link_to 'Edit', edit_report_path(report), class:"btn btn-info"
        %td= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"
- else
  %h1 Reports does not exists!

%br/

= link_to 'New Report', templates_reports_path, class: "btn btn-primary"

app/views/reports/new.html.haml
- title "New Report"

= link_to 'Back', templates_reports_path, class: "back-btn"

%h1 New report

= render 'form'

app/views/reports/show.html.haml
- title "Show Report: #{@report.title}"
= link_to 'Back', reports_path, class: "back-btn"
= print_notice notice

%p
  %strong Title:
  = @report.title
.reports
  - @items_value.each do |key, item_values|
    - item = Item.where(id: key)
    - unless item.empty?
      .report_item
        .report_item_title= item.first.name
        - item_values.each do |item_value|
          .report_item_value= item_value.value
.bottom_panel
  = link_to 'Edit', edit_report_path(@report), class:"btn btn-info"

app/views/reports/templates.html.haml
- title "Templates List"

= link_to 'Back', reports_path, class: "back-btn"

%h4 Please, choose template!

- unless @templates.empty?
	- @templates.each do |template|
		%p= link_to template.title, "#{new_report_path}?template=#{template.id}"
- else
	%h4 Template does not exist!